Repository EFUB-LakkuLakku/LakkuLakku-Back, pull requests merged in 2022-09, with the labels that each got.

#64 refactor: access token과 refresh token을 쿠키로 보내기
  src/main/java/com/efub/lakkulakku/domain/users/controller/LoginController.java
  src/main/java/com/efub/lakkulakku/domain/users/dto/LoginInfoDto.java
  src/main/java/com/efub/lakkulakku/domain/users/dto/LoginResDto.java
  src/main/java/com/efub/lakkulakku/domain/users/service/UsersService.java
  src/main/java/com/efub/lakkulakku/global/constant/ResponseConstant.java
Labels: 👀리뷰필요

#61 Feature/email
  src/main/java/com/efub/lakkulakku/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/efub/lakkulakku/domain/users/controller/LoginController.java
  src/main/java/com/efub/lakkulakku/domain/users/dao/CertificationDao.java
  src/main/java/com/efub/lakkulakku/domain/users/dto/CertificationReqDto.java
  src/main/java/com/efub/lakkulakku/domain/users/exception/CertificationCodeMismatchException.java
  src/main/java/com/efub/lakkulakku/domain/users/service/MailSendService.java
  src/main/java/com/efub/lakkulakku/domain/users/service/UsersService.java
  src/main/java/com/efub/lakkulakku/global/config/AppConfig.java
  src/main/java/com/efub/lakkulakku/global/constant/ResponseConstant.java
  src/main/java/com/efub/lakkulakku/global/exception/ErrorCode.java
  src/main/java/com/efub/lakkulakku/global/exception/GlobalExceptionHandler.java
Labels: 👀리뷰필요

#65 fix: 인증이 필요없는 url 추가
  src/main/java/com/efub/lakkulakku/global/config/AppConfig.java
Labels: 👀리뷰필요

#63 feat: 프로필 api 수정
  config/nginx/nginx.conf
  src/main/java/com/efub/lakkulakku/domain/file/repository/FileRepository.java
  src/main/java/com/efub/lakkulakku/domain/profile/controller/ProfileUpdateController.java
  src/main/java/com/efub/lakkulakku/domain/profile/service/ProfileService.java
Labels: 😉머지가능

#62 feat: 홈 api 분리, 댓글 스티커 저장
  src/main/java/com/efub/lakkulakku/domain/stickerResource/controller/StickerResourceController.java
  src/main/java/com/efub/lakkulakku/domain/stickerResource/service/StickerResourceService.java
  src/main/java/com/efub/lakkulakku/domain/users/controller/HomeController.java
  src/main/java/com/efub/lakkulakku/domain/users/service/UsersService.java
Labels: 😉머지가능

#66 refactor: 홈 api request parameter -> request body
  src/main/java/com/efub/lakkulakku/domain/users/controller/HomeController.java
Labels: 👀리뷰필요

#69 fix: PathVariable 을 RequestBody로 변경
  README.md
  src/main/java/com/efub/lakkulakku/domain/comment/controller/CommentController.java
  src/main/java/com/efub/lakkulakku/domain/comment/dto/CommentDeleteReqDto.java
  src/main/java/com/efub/lakkulakku/domain/comment/dto/CommentReqDto.java
  src/main/java/com/efub/lakkulakku/domain/comment/service/CommentService.java
Labels: 😉머지가능

#70 Develop
  src/main/java/com/efub/lakkulakku/domain/comment/controller/CommentController.java
  src/main/java/com/efub/lakkulakku/domain/comment/dto/CommentDeleteReqDto.java
  src/main/java/com/efub/lakkulakku/domain/comment/dto/CommentReqDto.java
  src/main/java/com/efub/lakkulakku/domain/comment/service/CommentService.java
Labels: 🐇Simple

#71 Develop
  src/main/java/com/efub/lakkulakku/domain/users/controller/LoginController.java
  src/main/java/com/efub/lakkulakku/domain/users/dto/EmailGetReqDto.java
Labels: 😉머지가능

#72 fix: 프론트 단에서 헤더에 있는 토큰값 보이지 않는 문제 해결
  src/main/java/com/efub/lakkulakku/global/config/AppConfig.java
Labels: 🚨긴급
