Repository EFUB-LakkuLakku/LakkuLakku-Back, pull requests merged in 2022-10, with the labels that each got.

#73 fix : 로그인, 토큰 재발급 로직 변경
  src/main/java/com/efub/lakkulakku/domain/users/controller/LoginController.java
  src/main/java/com/efub/lakkulakku/domain/users/dto/LoginInfoDto.java
  src/main/java/com/efub/lakkulakku/domain/users/dto/LoginResDto.java
  src/main/java/com/efub/lakkulakku/global/config/AppConfig.java
  src/main/java/com/efub/lakkulakku/global/config/jwt/JwtProvider.java
Labels: 🚨긴급

#74 Feature/email
  src/main/java/com/efub/lakkulakku/domain/users/controller/LoginController.java
  src/main/java/com/efub/lakkulakku/domain/users/dto/LoginInfoDto.java
  src/main/java/com/efub/lakkulakku/domain/users/dto/LoginResDto.java
  src/main/java/com/efub/lakkulakku/domain/users/dto/NewPwdReqDto.java
  src/main/java/com/efub/lakkulakku/domain/users/service/UsersService.java
  src/main/java/com/efub/lakkulakku/global/config/AppConfig.java
  src/main/java/com/efub/lakkulakku/global/config/jwt/JwtProvider.java
Labels: 👀리뷰필요

#75 fix : 이메일 인증 확인 로직 변경
  src/main/java/com/efub/lakkulakku/domain/users/controller/LoginController.java
  src/main/java/com/efub/lakkulakku/domain/users/dto/NewPwdReqDto.java
  src/main/java/com/efub/lakkulakku/domain/users/service/UsersService.java
Labels: 👀리뷰필요

#76 fix : 친구 조회, 친구 검색 오류
  src/main/java/com/efub/lakkulakku/domain/file/entity/File.java
  src/main/java/com/efub/lakkulakku/domain/friend/controller/FriendController.java
  src/main/java/com/efub/lakkulakku/domain/friend/dto/FriendResDto.java
  src/main/java/com/efub/lakkulakku/domain/friend/service/FriendService.java
Labels: 👀리뷰필요

#78 test : 토큰 시간 변경
  src/main/java/com/efub/lakkulakku/global/config/jwt/JwtProvider.java
Labels: 🐇Simple

#81 feat: SSE를 사용한 실시간 알림 기능 추가
  src/main/java/com/efub/lakkulakku/domain/comment/entity/Comment.java
  src/main/java/com/efub/lakkulakku/domain/comment/service/CommentService.java
  src/main/java/com/efub/lakkulakku/domain/file/entity/File.java
  src/main/java/com/efub/lakkulakku/domain/friend/controller/FriendController.java
  src/main/java/com/efub/lakkulakku/domain/friend/dto/FriendResDto.java
  src/main/java/com/efub/lakkulakku/domain/friend/entity/Friend.java
  src/main/java/com/efub/lakkulakku/domain/friend/exception/SelfFriendException.java
  src/main/java/com/efub/lakkulakku/domain/friend/service/FriendService.java
  src/main/java/com/efub/lakkulakku/domain/likes/entity/Likes.java
  src/main/java/com/efub/lakkulakku/domain/likes/service/LikesService.java
  src/main/java/com/efub/lakkulakku/domain/notification/controller/NotificationController.java
  src/main/java/com/efub/lakkulakku/domain/notification/dto/NotificationMapper.java
  src/main/java/com/efub/lakkulakku/domain/notification/dto/NotificationMessage.java
  src/main/java/com/efub/lakkulakku/domain/notification/dto/NotificationReqDto.java
  src/main/java/com/efub/lakkulakku/domain/notification/dto/NotificationResDto.java
  src/main/java/com/efub/lakkulakku/domain/notification/entity/Notification.java
  src/main/java/com/efub/lakkulakku/domain/notification/exception/SSEConnectionException.java
  src/main/java/com/efub/lakkulakku/domain/notification/repository/EmitterRepository.java
  src/main/java/com/efub/lakkulakku/domain/notification/repository/NotificationRepository.java
  src/main/java/com/efub/lakkulakku/domain/notification/service/NotificationService.java
  src/main/java/com/efub/lakkulakku/domain/users/controller/HomeController.java
  src/main/java/com/efub/lakkulakku/domain/users/dto/HomeMapper.java
  src/main/java/com/efub/lakkulakku/domain/users/dto/HomeResDto.java
  src/main/java/com/efub/lakkulakku/domain/users/service/UsersService.java
  src/main/java/com/efub/lakkulakku/global/config/AppConfig.java
  src/main/java/com/efub/lakkulakku/global/config/jwt/JwtProvider.java
  src/main/java/com/efub/lakkulakku/global/config/notification/AsyncConfig.java
  src/main/java/com/efub/lakkulakku/global/config/notification/NotificationListener.java
  src/main/java/com/efub/lakkulakku/global/exception/ErrorCode.java
Labels: enhancement, 😉머지가능

#83 fix: 홈 api request body -> param
  src/main/java/com/efub/lakkulakku/domain/users/controller/HomeController.java
Labels: enhancement, 🚨긴급
