Repository EFUB-LakkuLakku/LakkuLakku-Back, pull requests merged in 2022-11, with the labels that each got.

#85 fix : 토큰 시간 변경
  src/main/java/com/efub/lakkulakku/global/config/jwt/JwtProvider.java
Labels: 👀리뷰필요

#87 feat: 다이어리 조회 api와 다이어리 댓글 조회 api 분리
  src/main/java/com/efub/lakkulakku/domain/diary/controller/DiaryController.java
  src/main/java/com/efub/lakkulakku/domain/diary/dto/DiaryLookupResDto.java
  src/main/java/com/efub/lakkulakku/domain/diary/dto/DiaryMapper.java
  src/main/java/com/efub/lakkulakku/domain/diary/service/DiaryService.java
Labels: 🐇Simple

#89 Feature/view count
  src/main/java/com/efub/lakkulakku/domain/diary/controller/DiaryController.java
  src/main/java/com/efub/lakkulakku/domain/diary/dto/DiaryMapper.java
  src/main/java/com/efub/lakkulakku/domain/diary/dto/DiaryResDto.java
  src/main/java/com/efub/lakkulakku/domain/diary/entity/Diary.java
  src/main/java/com/efub/lakkulakku/domain/diary/service/DiaryService.java
Labels: enhancement
